version: 2.0
jobs:
  package:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout:
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt --user
      - store_artifacts:
          path: app
          destination: prefix
  test:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout:
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt --user
    test:
      - run:
          name: Run tests
          command: |
            flake8 .
            mkdir test-reports
            /home/circleci/.local/bin/pytest --junitxml=test-reports/junit.xml tests.py
      - store_test_results:
          path: test-reports/junit.xml
workflows:
  version: 2
  package-and-test:
    jobs:
      - package
      - test:
          requires:
            - build
