version: 2.0
jobs:
  build:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout:
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt --user
      - run:
          name: Run tests
          command: |
            mkdir test-reports
            /home/circleci/.local/bin/pytest --junitxml=test-reports/junit.xml tests.py

      - store_test_results:
          path: test-reports/junit.xml

      - store_artifacts:
          path: build/libs
          destination: prefix
workflows:
  version: 2
  build:
    - build