version: 2.0
jobs:
  build:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout:
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt --user
      - run:
          name: Run tests
          command: |
            pytest tests.py

      - store_test_results:
          path: build/test-results

      - store_artifacts:
          path: build/libs
          destination: prefix
