version: 2.0
jobs:
  package:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout:
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt --user
      - store_artifacts:
          path: app
          destination: prefix
  test:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout:
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt --user
      - run:
          name: Run tests
          command: |
            /home/circleci/.local/bin/flake8 .
            mkdir test-reports
            /home/circleci/.local/bin/pytest --junitxml=test-reports/junit.xml tests.py
      - store_test_results:
          path: test-reports/junit.xml
  lint:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout:
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt --user
      - run:
          name: Run lint
          command: |           
            mkdir test-reports 
            /home/circleci/.local/bin/flake8 . --output-file=test-reports/flake8.txt --tee
      - store_test_results:
          path: test-reports/flake8.txt
  dockerize:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t $DOCKER_USER/kebabanon:$CIRCLE_SHA1 .
      - run: docker push $DOCKER_USER/kebabanon:$CIRCLE_SHA1
workflows:
  version: 2
  package-and-test:
    jobs:
      - package
      - test:
          requires:
            - package
      - lint:
          requires:
            - package
            - test
      - dockerize:
          requires:
            - test
